import Head from 'next/head';
import Link from 'next/link';
import Advertisement from '../components/advertisement';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Link href="/advertisement"><a>Advertisement</a></Link> */}
      <Advertisement />
    </>
  );
}
